/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paint;

import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Merna
 */
public class drawSquare extends javax.swing.JFrame implements Node {
drawingEngineData d;
private Node n;
//Graphics g;
JComboBox selector;
    /**
     * Creates new form drawSquare
     */
    public drawSquare(drawingEngineData d, JComboBox<String> selector) {
        initComponents();
        this.d=d;
        //this.g=g;
        this.selector=selector;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x_component = new javax.swing.JTextField();
        y_component = new javax.swing.JTextField();
        sidelength = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        draw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        x_component.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_componentActionPerformed(evt);
            }
        });

        y_component.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_componentActionPerformed(evt);
            }
        });

        sidelength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidelengthActionPerformed(evt);
            }
        });

        jLabel1.setText(" X-coordinates");

        jLabel2.setText(" Y-coordinates");

        jLabel3.setText("Side Length");

        draw.setText("Draw");
        draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidelength, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_component, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_component, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(draw)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x_component, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y_component, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidelength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(draw)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x_componentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_componentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_componentActionPerformed

    private void y_componentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_componentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y_componentActionPerformed

    private void sidelengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidelengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidelengthActionPerformed

    private void drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawActionPerformed
        // TODO add your handling code here:
          String x= x_component.getText();
        String y =y_component.getText();
        String s= sidelength.getText();
         if(x.isEmpty()||y.isEmpty()||s.isEmpty())
            JOptionPane.showMessageDialog(null, "you should enter all the fields");
        else if(Integer.parseInt(x)<0||Integer.parseInt(y)<0||Integer.parseInt(s)<0)
            JOptionPane.showMessageDialog(null, "you should enter positive numbers");
         else
        {
        int X= Integer.parseInt(x);
        int Y= Integer.parseInt(y);
        int s1= Integer.parseInt(s);
        Point p= new Point(X,Y);
        Rectangle sq= new Rectangle(p,s1,s1);
        //sq.setPosition(p);
        sq.setShapeName("square");
        sq.generateKey();
        //sq.draw(g);
        d.addShape(sq);
        d.refresh();
        selector.addItem(sq.getName_key());
        this.setVisible(false);
          ((JFrame)getParentNode()).setVisible(true);
        }
    }//GEN-LAST:event_drawActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton draw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField sidelength;
    private javax.swing.JTextField x_component;
    private javax.swing.JTextField y_component;
    // End of variables declaration//GEN-END:variables

      @Override
     public Node getParentNode() {
        return n;
    }

    @Override
     public void setParentNode(Node node) {
        this.n=node;
    }
}
